spring:
  application:
    name: lotto-api-202030416
  graphql:
    graphiql:
      enabled: true # graphiql? ?? ??? ?? ?? (localhost:8080/graphiql)
      printer:
        enabled: true # show-sql? ?? graphql ??? ?? ??
server:
  port: 8081